@isTest
private class PermSetControllerTest {

    @isTest static void testPermSetAssignmentList(){

        Test.startTest();

        Test.StopTest();
    }

    @isTest static void testPermSetUserCount(){
        Test.startTest();
        
        Test.StopTest();

    }

    @isTest static void testfindUsers(){
        Test.startTest();
        
        Test.StopTest();

    }

    @isTest static void testPermSetList(){
        Test.startTest();
        
        Test.StopTest();

    }
}
